### ISSUE TITLE
export guid of referenced entity to csv file

### ISSUE THREAD

**Issue by milossramek** [enu-sav/RS#11]
We need to know guid of a referenced entity  (illustration) to export nodes. This is currently not possible, but http://drupal.stackexchange.com/questions/30005/url-and-guid-values-from-feed-import indicates that this might be possible. May be implemented in Views or through customized Node display.

**Comment by miromichalicka** [comment]
Why do we need to know GIUD?

**Comment by milossramek** [comment]
Illustration GUID is used to create reference from 'importovane heslo' item to its illustrations when importing from doc files. Illustration GUID is used since we know it in advance.
We plan to add more illustrations by reimporting items, so we need GUID because of the same reason.

**Comment by milossramek** [comment]
I think that I have a workaround (base on external script), so we may close this one.
