### ISSUE TITLE
cannot revert features

### ISSUE THREAD

**Issue by milossramek** [enu-sav/RS#13]
I am not able to revert features in CTools on dev.beliana after git pull. I've tried both the web interface and drush @dev features-revert-all
If successfull the 'Opraviť importované' item should vanish from the menu bar of all roles except for iredaktor.

**Comment by miromichalicka** [comment]
Can you specify for which roles it isn't working as expected? I tried it with user 1657 and it seems to be working fine

**Comment by milossramek** [comment]
Hm, the problem is gone, there are no features to be reverted now. But I really tried to do revert them maybe 4 times today morming :). The item is gone from the menubar, too. So lets close the issue.
