### ISSUE TITLE
Necessary modifications in the function beliana_merge

### ISSUE THREAD

**Issue by milossramek** [enu-sav/RS#16]
Function beliana_merge was written long time ago, the fields of the Heslo type has meanwhile changed. Required changes:  

field_lexikalna_skupina - OK
field_komentar_instrukcie - spojiť, oddeliť "\n"
field_text_hesla - uz sa spaja, pridat oddelovac "\</p\>\n\<p\>"
field_text_z_gh - spojiť, oddelit "\n"
field_datum - resetovat, obe polozky maju byt prazdne
field_ilustracia - prevziat vsetky polozky
field_na_zoradenie - OK
path - ponechat path 1. zlucovaneho hesla (tak to asi je teraz), path v povodnych heslach zmazat. Zda sa, že teraz  ma nove heslo rovnaky path ako prve zo zoznamu. Neskor po upravach sa  path noveho hesla moze nejako zmenit - to nechceme, lebo na neho moze byt spraveny odkaz.
field_atributy - spojit, oddelit čiarkou
field_taxsubor - OK
field_zlucene_z - OK
field_zlucene_do - OK
field_spravit_1_korekturu - OK
field_povodne_lexikalne_skupiny - OK
field_vyplatit - resetovať, ma byt prazdne
field_errta - resetovať, ma byt prazdne

References to nonexistent fields should be removed: field_image, field_text_k_ilustraciam, field_autor_povodneho_textu and maybe others

**Comment by miromichalicka** [comment]
Please test 2281fdf342d96d89875f48287da74d23de698a8f

**Comment by milossramek** [comment]
Tested, works, closing
