### ISSUE TITLE
bug vo Views - voľba Nie je prázdne

### ISSUE THREAD

**Issue by milossramek** [enu-sav/RS#2]
tyka sa nas tento bug: https://www.drupal.org/node/1249684
Vyskusat si to mozno tu: http://dev.encyclopaedia.sk/vyh%C4%BEada%C5%A5
V Text hesla zvoľte Nie je prázdne (Text hesla zmizne, objaví sa až po
odhlaseni a prihlaseni pouzivatela

V Text hesla to nie je problem (kto by Nie je prazdne volil?) ale práve
spm pridal pole Errata, a tam je to zaujímavé.
Je ten posledný patch použiteľný?

**Comment by miromichalicka** [comment]
Patch pouzitelny, aplikovany aj na zivu verziu.
