### ISSUE TITLE
drush sql-drop fails

### ISSUE THREAD

**Issue by milossramek** [enu-sav/RS#22]
It looks like that since the upgrade the 'drush sql-drop' command fails:
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

As dot cannot be in database name (http://stackoverflow.com/questions/776123/does-mysql-allows-to-create-database-with-dot), I've renamed the databases (drop & create) using underscores.
However, it still does not work :)

Without dropping the database one cannot synchronize with orig, it results to numerous errors (duplicated tables etc).

**Comment by miromichalicka** [comment]
Drush version updated to 8.1.7, now it's working fine.
